# This file is intentionally empty as we don't have any sensitive information to store
# Add any API keys or sensitive data here if needed in the future 

mongodb_uri = "mongodb+srv://zapperwing:NXRcnYPShKScMtXD@cluster0.fzmmg3n.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0" 